library(tidyverse)
## Input the data
df <- read.csv("PROMIS_cleaned_ALL.csv")
df <- df %>%
  select(-c(1:2))
# subset children 8-17
df <- df[df$P_age_g != "g1:2-7",]
# View(CHL)
PAT <- df %>%
  select(1:441, "E_refer2", "E_D")
CHL <- df %>%
  select(3,442:793, "E_refer2", "E_D")


## Rescale
### Step 1: the higher the better
################################ Children ######################

### Combine some options of some variables 
CHL$C_TEETH_P <- NA
CHL$C_TEETH_P[CHL$C_TEETHB + CHL$C_TEETHC + CHL$C_TEETHD == 0] <- 0
CHL$C_TEETH_P[CHL$C_TEETHB + CHL$C_TEETHC + CHL$C_TEETHD > 0] <- 1

CHL$C_COLOR_WH <- NA
CHL$C_COLOR_WH[CHL$C_COLORA + CHL$C_COLORB == 0] <- 0
CHL$C_COLOR_WH[CHL$C_COLORA + CHL$C_COLORB > 0] <- 1

CHL$C_COLOR_BAD <- NA
CHL$C_COLOR_BAD[CHL$C_COLORC + CHL$C_COLORD + CHL$C_COLORE + CHL$C_COLORF == 0] <- 0
CHL$C_COLOR_BAD[CHL$C_COLORC + CHL$C_COLORD + CHL$C_COLORE + CHL$C_COLORF > 0] <- 1

CHL$C_BRUSH <- 1
CHL$C_BRUSH[CHL$C_BRUSH * CHL$C_BURSHTB + CHL$C_BURSHTC == 1] <- 2
CHL$C_BRUSH[CHL$C_BURSHTD == 1] <- 0
CHL$C_BRUSH[is.na(CHL$C_DENTIST)] <- NA

### Select all the wanted variables
CHL_want <- CHL[, match(c( "P_ID",
                       "C_PHYFUNC", 
                       "C_SWALLOW", 
                       "C_HEALT", 
                       "C_PAINPROA",
                       "C_TEETH_P",
                       "C_TEETHA", 
                       "C_COLOR_WH", 
                       "C_COLOR_BAD",
                       "C_BREATH", 
                       "C_CHOPI", 
                       "C_CHOPB", 
                       "C_CHOPF", 
                       "C_SCHMISS", 
                       "C_CHOPH", 
                       "C_CHOPG", 
                       "C_CHOPK", 
                       "C_CHOPL", 
                       "C_PAINPROD", 
                       "C_CHOPC", 
                       "C_CHOPD", 
                       "C_CHOPE", 
                       "C_PAINPROB", 
                       "C_CHOPA", 
                       "C_PAIN", 
                       "C_PAINPROF", 
                       "C_PAINPROE", 
                       "C_PAINPROC", 
                       "C_PAINDISC", 
                       "C_AFRAID", 
                       "C_ANXIET2C", 
                       "C_ANXIETY", 
                       "C_BREATH1", 
                       "C_WORRY", 
                       "C_DEVELOP", 
                       "C_DEVELOP1", 
                       "C_LIFECHAN", 
                       "C_LONGEV", 
                       "C_LONGEV1", 
                       "C_LONGEV3", 
                       "C_HAPPY", 
                       "C_TEETH2", 
                       "C_SOCCOMP", 
                       "C_TEELOOK", 
                       "C_TEETH1", 
                       "C_TVOH", 
                       "C_BRUSH",
                       "C_FLOSS", 
                       "C_TOBACCO3", 
                       "C_ANXIET2E", 
                       "C_ANXIET2F", 
                       "C_ANXIET2G", 
                       "C_ANXIET2H", 
                       "C_SOCCOMP1", 
                       "C_SOCCOMP2", 
                       "C_CHOPJ", 
                       "C_SELFEFF", 
                       "C_SELFEFF1", 
                       "C_OHEFFECT", 
                       "C_TEELOOK1", 
                       "C_BELIEF2", 
                       "C_TEELOOK2", 
                       "C_HABIT", 
                       "C_SOCNETA", 
                       "C_SOCNETB", 
                       "C_SOCNETC", 
                       "C_SOCNETE", 
                       "C_SOCNETF", 
                       "C_SOCNETG", 
                       "C_SOCNET2A", 
                       "C_SOCNET2B", 
                       "C_SOCNET2C", 
                       "C_SOCNET2D", 
                       "C_SOCNET2E", 
                       "C_SOCNET1A", 
                       "C_SOCNET1B", 
                       "C_SOCNET1D", 
                       "C_SOCNET1E", 
                       "C_SOCNET1F", 
                       "C_SOCNET1G", 
                       "C_SOCNET1H", 
                       "C_ANXIET2A", 
                       "C_ANXIET2B", 
                       "C_ANXIET2D", 
                       "C_ANXIET2I", 
                       "C_ANXIET2J", 
                       "C_ANXIET2K", 
                       "C_ANXIET2L", 
                       "C_ANXIET2M",
                       "C_MISSINGB",
                       "C_BPPTOOTH",
                       "C_HURT",
                       "C_ACHE",
                       "C_MISSING",
                       "C_GUM",
                       "C_GUM_B",
                       "C_DENTIST",
                       "C_VISIT",
                       "C_CARE",
                       "C_CAVITYAW",
                       "C_CAVITYTD",
                       "C_TOOTHMIS",	
                       "C_DISCCOLD",	
                       "C_DISCHOT",	
                       "C_DISCMFT",
                       "C_CAVFRONT",
                       "C_CAVBACK",	
                       "C_FILLINGA",
                       "C_FILLINGT",
                       "C_FILLING1",
                       "C_CROWNA",	
                       "C_CROWNT",	
                       "C_CROWN1",	
                       "C_DRILL",
                       "C_SEALANTA",
                       "C_SEALANTT",
                       "C_SEALANT1",
                       "C_EXTBT",	
                       "C_EXTPT",
                       "C_BLEEDBR",
                       "C_PROFILE",
                       "C_SNACK",
                       "C_SUGAR1",
                       "C_SUGAR2",
                       "C_LENGTHB",
                       "C_ELECBR",
                       "C_FLOSST",
                       "E_refer2", 
                       "E_D"), names(CHL))]

CHL_opp <- match(c( "C_SWALLOW", 
                    "C_HEALT", 
                    "C_PAINPROA", 
                    "C_TEETH_P", 
                    "C_COLOR_BAD", 
                    "C_SCHMISS", 
                    "C_PAINPROD", 
                    "C_PAINPROB", 
                    "C_PAINPROF", 
                    "C_PAINPROE", 
                    "C_PAINPROC", 
                    "C_AFRAID", 
                    "C_ANXIET2C", 
                    "C_ANXIETY", 
                    "C_LONGEV", 
                    "C_LONGEV1", 
                    "C_LONGEV3", 
                    "C_HAPPY", 
                    "C_TEETH2", 
                    "C_SOCCOMP", 
                    "C_TEELOOK", 
                    "C_TEETH1", 
                    "C_TOBACCO3", 
                    "C_ANXIET2E", 
                    "C_ANXIET2F", 
                    "C_ANXIET2G", 
                    "C_ANXIET2H", 
                    "C_SOCCOMP2", 
                    "C_SELFEFF", 
                    "C_SELFEFF1", 
                    "C_TEELOOK1", 
                    "C_TEELOOK2", 
                    "C_ANXIET2A", 
                    "C_ANXIET2B", 
                    "C_ANXIET2D", 
                    "C_ANXIET2I", 
                    "C_ANXIET2J", 
                    "C_ANXIET2K", 
                    "C_ANXIET2L", 
                    "C_ANXIET2M",
                    "C_MISSINGB",
                    "C_BPPTOOTH",
                    "C_HURT",
                    "C_ACHE",
                    "C_MISSING",
                    "C_GUM",
                    "C_GUM_B",
                    "C_VISIT",
                    "C_CARE",
                    "C_DISCCOLD",	
                    "C_DISCHOT",	
                    "C_DISCMFT",
                    "C_CAVFRONT",
                    "C_CAVBACK",	
                    "C_FILLING1",
                    "C_CROWN1",	
                    "C_SEALANT1",
                    "C_EXTBT",	
                    "C_EXTPT",
                    "C_FLOSST"
), names(CHL_want))
CHL_want[, CHL_opp] <- t(apply(CHL_want[, CHL_opp], 2, max, na.rm = TRUE) - t(CHL_want[, CHL_opp]))
CHL_scaled <- as.data.frame(CHL_want)
CHL_scaled[,-1] <- t(t(CHL_scaled[,-1]) - apply(CHL_scaled[,-1], 2, min, na.rm=TRUE)) 
write.csv(CHL_scaled, "C:/Users/Jishan Wu/Desktop/Claire/CHL_scaled.csv")

################################ Parent ######################

### Combine some options of some variables 
PAT$P_TEETH_P <- 0
PAT$P_TEETH_P[PAT$P_TEETHB + PAT$P_TEETHC + PAT$P_TEETHD > 0] <- 1

PAT$P_COLOR_WH <- 0
PAT$P_COLOR_WH[PAT$P_COLORA + PAT$P_COLORB > 0] <- 1

PAT$P_COLOR_BAD <- 0
PAT$P_COLOR_BAD[PAT$P_COLORC + PAT$P_COLORD + PAT$P_COLORE + PAT$P_COLORF > 0] <- 1

PAT$P_BRUSH <- 1
PAT$P_BRUSH[PAT$P_BURSHTA * PAT$P_BURSHTB + PAT$P_BURSHTC == 1] <- 2
PAT$P_BRUSH[PAT$P_BURSHTD == 1] <- 0
PAT$P_LENGTHB[PAT$P_LENGTHB == 9] <- 3
PAT$P_BRUSH[is.na(PAT$P_DENTIST)] <- NA

PAT_want <- PAT[, match(c( "P_ID",
                           "P_PHYFUNC",
                           "P_SWALLOW",
                           "P_CLDHEALT",
                           "P_HEALTH",
                           "P_SELFEFF2",
                           "P_COLOR_WH",
                           "P_COLOR_BAD",
                           "P_TEETH_P",
                           "P_TEETHA",
                           "P_BREATH",
                           "P_SCHMISS",
                           "P_CHOPI",
                           "P_CHOPK",
                           "P_CHOPL",
                           "P_CHOPB",
                           "P_CHOPF",
                           "P_CHOPG",
                           "P_CHOPH",
                           "P_PAIN",
                           "P_CHOPA",
                           "P_CHOPC",
                           "P_CHOPD",
                           "P_CHOPE",
                           "P_ACCESS",
                           "P_AFRAID",
                           "P_BREATH1",
                           "P_WORRY",
                           "P_ANXIETY",
                           "P_ANXIETY2",
                           "P_TEETH1",
                           "P_TEETH2",
                           "P_SOCCOM2",
                           "P_SH1",
                           "P_DEVELOP",
                           "P_DEVELOP1",
                           "P_LONGEV",
                           "P_LONGEV1",
                           "P_LONGEV3",
                           "P_LIFECHAN",
                           "P_ACCESS1",
                           "P_ACCESS5",
                           "P_ACCESS6",
                           "P_SELFEFF7",
                           "P_SELFEFF5",
                           "P_SELFEFF6",
                           "P_BELIEF",
                           "P_CIGARET",
                           "P_CHOPJ",
                           "P_SELFEFF",
                           "P_SELFEFF1",
                           "P_OHEFFECT",
                           "P_SOCNET1A",
                           "P_SOCNET1B",
                           "P_SOCNET1C",
                           "P_SOCNET1D",
                           "P_SOCNET1E",
                           "P_SOCNET1F",
                           "P_SOCNET1G",
                           "P_SOCNET2A",
                           "P_SOCNET2B",
                           "P_SOCNET2C",
                           "P_SOCNET2D",
                           "P_SOCNET2E",
                           "P_ACCESS8",
                           "P_MISSINGB",
                           "P_BPPTOOTH",
                           "P_HURT",
                           "P_ACHE",
                           "P_MISSING",
                           "P_GUM",
                           "P_GUM_B",
                           "P_DENTIST",
                           "P_VISIT",
                           "P_CARE",
                           "P_CAVITYAW",
                           "P_CAVITYTD",
                           "P_TOOTHMIS",	
                           "P_DISCCOLD",	
                           "P_DISCHOT",	
                           "P_DISCMFT",
                           "P_CAVFRONT",
                           "P_CAVBACK",	
                           "P_FILLINGA",
                           "P_FILLINGT",
                           "P_FILLING1",
                           "P_CROWNA",	
                           "P_CROWNT",	
                           "P_CROWN1",	
                           "P_DRILL",
                           "P_SEALANTA",
                           "P_SEALANTT",
                           "P_SEALANT1",
                           "P_EXTBT",	
                           "P_EXTPT",
                           "P_BLEEDBR",
                           "P_PROFILE",
                           "P_SNACK",
                           "P_SUGAR1",
                           "P_SUGAR2",
                           "P_BRUSH",
                           "P_LENGTHB",
                           "P_ELECBR",
                           "P_INS",
                           "P_FLOSST",
                           "E_refer2", 
                           "E_D"), names(PAT))]

PAT_opp <- match(c( "P_SWALLOW",
                    "P_CLDHEALT",
                    "P_HEALTH",
                    "P_SELFEFF2",
                    "P_COLOR_BAD",
                    "P_TEETH_P",
                    "P_SCHMISS",
                    "P_ACCESS",
                    "P_AFRAID",
                    "P_ANXIETY",
                    "P_ANXIETY2",
                    "P_TEETH1",
                    "P_TEETH2",
                    "P_SOCCOM2",
                    "P_SH1",
                    "P_LONGEV",
                    "P_LONGEV1",
                    "P_LONGEV3",
                    "P_ACCESS1",
                    "P_ACCESS5",
                    "P_ACCESS6",
                    "P_BELIEF",
                    "P_CIGARET",
                    "P_SELFEFF",
                    "P_SELFEFF1",
                    "P_ACCESS8",
                    "P_MISSINGB",
                    "P_BPPTOOTH",
                    "P_HURT",
                    "P_ACHE",
                    "P_MISSING",
                    "P_GUM",
                    "P_GUM_B",
                    "P_VISIT",
                    "P_CARE",
                    "P_DISCCOLD",	
                    "P_DISCHOT",	
                    "P_DISCMFT",
                    "P_CAVFRONT",
                    "P_CAVBACK",	
                    "P_FILLING1",
                    "P_CROWN1",	
                    "P_SEALANT1",
                    "P_EXTBT",	
                    "P_EXTPT",
                    "P_FLOSST"), names(PAT_want))
#rescale
PAT_want[, PAT_opp] <- t(apply(PAT_want[, PAT_opp], 2, max, na.rm = TRUE) - t(PAT_want[, PAT_opp])) + 1
PAT_scaled <- as.data.frame(PAT_want)
#every variable starts from 0
PAT_scaled[,-1] <- t(t(PAT_scaled[,-1]) - apply(PAT_scaled[,-1], 2, min, na.rm=TRUE))
View(PAT_scaled)
write.csv(PAT_scaled, "PAT_scaled.csv")


